import React, { useState, useMemo, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, DollarSign, X, Settings, Heart, AlertCircle, Edit2, TrendingUp, Shirt } from 'lucide-react';
import { initializeApp } from 'firebase/app';
import { getAuth, signInAnonymously, signInWithCustomToken, onAuthStateChanged } from 'firebase/auth';
import { getFirestore, doc, setDoc, onSnapshot, DocumentData, Unsubscribe } from 'firebase/firestore';
import { GoogleGenAI } from "@google/genai";

import { Category, Expense, CatMood, CatStage, CATEGORY_COLORS, CatId, HatId, CAT_PROFILES, HAT_PROFILES } from './types';
import { ThreeDCat } from './components/ThreeDCat';
import { ExpensePieChart } from './components/Charts';

// --- INITIAL CONSTANTS ---
const INITIAL_BUDGET = 2000;
const LOCAL_STORAGE_KEY = 'purrbudget_data';
const PREFS_STORAGE_KEY = 'purrbudget_prefs';

// --- SOUND ASSETS (Base64 for reliability) ---
// Short "Bubble Pop" sound
const POP_SOUND_URL = "data:audio/wav;base64,UklGRi4AAABXQVZFZm10IBAAAAABAAEAQB8AAEAfAAABAAgAZGF0YQAAAAA="; 
// *Note*: The above is a dummy empty header for safety. Real base64 below.
// Actually, let's use a very short synthetic beep generated by Web Audio API for pop, 
// but since the prompt asks for "Bubble pop ASMR", I will try to use a real small buffer in code or a simulation.
// To keep it simple and working: we will use a simple function to synthesize a pop.

// --- GLOBAL DECLARATIONS FOR FIREBASE ---
declare global {
  var __app_id: string | undefined;
  var __firebase_config: string | undefined;
  var __initial_auth_token: string | undefined;
}

export default function App() {
  // --- FIREBASE STATE ---
  const [db, setDb] = useState<any>(null);
  const [userId, setUserId] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  // --- APP STATE ---
  const [expenses, setExpenses] = useState<Expense[]>([]);
  const [budget, setBudget] = useState(INITIAL_BUDGET);
  
  // Customization State
  const [catId, setCatId] = useState<CatId>('pertti');
  const [hatId, setHatId] = useState<HatId>('none');
  const [isPurring, setIsPurring] = useState(false);
  const [catInsight, setCatInsight] = useState<string>('');

  // Modals
  const [showAddModal, setShowAddModal] = useState(false);
  const [showChartModal, setShowChartModal] = useState(false);
  const [showBudgetModal, setShowBudgetModal] = useState(false);
  const [showWardrobeModal, setShowWardrobeModal] = useState(false);

  // --- AUDIO LOGIC ---
  const playPopSound = useCallback(() => {
    // Synthesize a soft pop sound using Web Audio API to avoid external asset dependency
    const AudioContext = window.AudioContext || (window as any).webkitAudioContext;
    if (!AudioContext) return;
    
    const ctx = new AudioContext();
    const osc = ctx.createOscillator();
    const gain = ctx.createGain();
    
    osc.frequency.setValueAtTime(300, ctx.currentTime);
    osc.frequency.exponentialRampToValueAtTime(800, ctx.currentTime + 0.1);
    
    gain.gain.setValueAtTime(0.1, ctx.currentTime);
    gain.gain.exponentialRampToValueAtTime(0.01, ctx.currentTime + 0.1);
    
    osc.connect(gain);
    gain.connect(ctx.destination);
    
    osc.start();
    osc.stop(ctx.currentTime + 0.15);
  }, []);

  const playPurrSound = useCallback(() => {
     // Simulated Purr (Low frequency amplitude modulation)
     if (isPurring) return; // Don't stack
     setIsPurring(true);
     
     const AudioContext = window.AudioContext || (window as any).webkitAudioContext;
     if (!AudioContext) return;
     const ctx = new AudioContext();

     const noiseBufferSize = ctx.sampleRate * 2.0; // 2 seconds
     const buffer = ctx.createBuffer(1, noiseBufferSize, ctx.sampleRate);
     const data = buffer.getChannelData(0);
     for (let i = 0; i < noiseBufferSize; i++) {
         data[i] = Math.random() * 2 - 1;
     }

     const noise = ctx.createBufferSource();
     noise.buffer = buffer;
     noise.loop = true;

     // Filter to make it low rumble
     const filter = ctx.createBiquadFilter();
     filter.type = 'lowpass';
     filter.frequency.value = 100;

     // Gain to modulate loudness (The "Rhythmic" purr)
     const gain = ctx.createGain();
     const lfo = ctx.createOscillator();
     lfo.type = 'sine';
     lfo.frequency.value = 25; // 25Hz purr rattle
     const lfoGain = ctx.createGain();
     lfoGain.gain.value = 500; // Depth of modulation

     noise.connect(filter);
     filter.connect(gain);
     gain.connect(ctx.destination);
     
     noise.start();
     
     // Fade out after 2 seconds
     gain.gain.setValueAtTime(0.5, ctx.currentTime);
     gain.gain.exponentialRampToValueAtTime(0.001, ctx.currentTime + 2.5);
     noise.stop(ctx.currentTime + 2.5);

     setTimeout(() => setIsPurring(false), 2500);
  }, [isPurring]);

  // Wrapper for interactions to include sound
  const withSound = (fn?: () => void) => () => {
      playPopSound();
      if (fn) fn();
  };


  // --- INITIALIZATION ---
  useEffect(() => {
    // Load Customization Prefs
    const prefs = localStorage.getItem(PREFS_STORAGE_KEY);
    if (prefs) {
        try {
            const parsed = JSON.parse(prefs);
            if (parsed.catId) setCatId(parsed.catId);
            if (parsed.hatId) setHatId(parsed.hatId);
        } catch(e) {}
    }

    const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';
    const firebaseConfigRaw = typeof __firebase_config !== 'undefined' ? __firebase_config : '{}';
    const initialAuthToken = typeof __initial_auth_token !== 'undefined' ? __initial_auth_token : undefined;
    
    let firebaseConfig = {};
    try {
      firebaseConfig = JSON.parse(firebaseConfigRaw);
    } catch (e) {
      console.warn("Error parsing firebase config, defaulting to empty.");
    }

    if (!Object.keys(firebaseConfig).length) {
        const localData = localStorage.getItem(LOCAL_STORAGE_KEY);
        if (localData) {
            try {
                const parsed = JSON.parse(localData);
                if (parsed.budget) setBudget(parsed.budget);
                if (parsed.expenses) {
                    setExpenses(parsed.expenses.map((e: any) => ({
                        ...e,
                        date: new Date(e.date)
                    })));
                }
            } catch (e) { console.error(e); }
        }
        setIsLoading(false);
        return;
    }
    
    try {
        const app = initializeApp(firebaseConfig);
        const firestoreDb = getFirestore(app);
        const auth = getAuth(app);
        setDb(firestoreDb);
        
        const unsubscribeAuth = onAuthStateChanged(auth, (user) => {
            if (user) {
                setUserId(user.uid);
            } else {
                (async () => {
                    try {
                        if (initialAuthToken) await signInWithCustomToken(auth, initialAuthToken);
                        else await signInAnonymously(auth);
                    } catch (error) { setIsLoading(false); }
                })();
            }
        });
        return () => unsubscribeAuth();
    } catch (err) { setIsLoading(false); }
  }, []);

  useEffect(() => {
    // Save prefs whenever they change
    localStorage.setItem(PREFS_STORAGE_KEY, JSON.stringify({ catId, hatId }));
  }, [catId, hatId]);

  // --- REAL-TIME SYNC ---
  useEffect(() => {
    let unsubscribe: Unsubscribe | undefined;
    const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';

    if (db && userId) {
      const docRef = doc(db, 'artifacts', appId, 'users', userId, 'budget_data', 'user_budget');
      unsubscribe = onSnapshot(docRef, (docSnap) => {
        if (docSnap.exists()) {
          const data = docSnap.data() as DocumentData;
          setBudget(data.budget || INITIAL_BUDGET);
          const loadedExpenses: Expense[] = (data.expenses || []).map((e: any) => ({
             ...e,
             date: e.date && typeof e.date.toDate === 'function' ? e.date.toDate() : new Date(e.date)
          }));
          setExpenses(loadedExpenses);
        } else {
          setBudget(INITIAL_BUDGET);
          setExpenses([]);
        }
        setIsLoading(false);
      });
    } else if (db && !userId) {
        setIsLoading(true);
    }
    return () => { if (unsubscribe) unsubscribe(); };
  }, [db, userId]);

  // --- SAVE DATA ---
  const saveData = async (newBudget: number, newExpenses: Expense[]) => {
    if (db && userId) {
        const appId = typeof __app_id !== 'undefined' ? __app_id : 'default-app-id';
        const docRef = doc(db, 'artifacts', appId, 'users', userId, 'budget_data', 'user_budget');
        await setDoc(docRef, { budget: newBudget, expenses: newExpenses }).catch(console.error);
    } else {
        localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify({ budget: newBudget, expenses: newExpenses }));
    }
  };

  const handleAddExpense = (amount: number, category: Category, note: string) => {
    const newExpense: Expense = {
      id: Math.random().toString(36).substr(2, 9),
      amount,
      category,
      date: new Date(),
      note
    };
    const newExpenses = [...expenses, newExpense];
    setExpenses(newExpenses); 
    setShowAddModal(false);
    saveData(budget, newExpenses);
  };

  const handleUpdateBudget = (newBudget: number) => {
    setBudget(newBudget);
    setShowBudgetModal(false);
    saveData(newBudget, expenses);
  };

  // --- DERIVED STATE ---
  const totalSpent = expenses.reduce((sum, e) => sum + e.amount, 0);
  const spendingRatio = budget > 0 ? totalSpent / budget : 1;
  const totalXP = expenses.length * 25;
  const growthProgress = Math.min((totalXP % 100) / 100, 1);
  
  const stage: CatStage = useMemo(() => {
    if (totalXP < 100) return 'kitten';
    if (totalXP < 300) return 'teen';
    return 'adult';
  }, [totalXP]);

  const mood: CatMood = useMemo(() => {
    if (spendingRatio > 1.0) return 'angry';
    if (spendingRatio > 0.75) return 'worried';
    return 'happy';
  }, [spendingRatio]);

  const chartData = useMemo(() => {
    const map: Record<string, number> = {};
    Object.values(Category).forEach(k => map[k] = 0);
    expenses.forEach(e => {
      if (map[e.category] !== undefined) map[e.category] += e.amount;
    });
    return Object.entries(map).map(([name, value]) => ({
      name,
      value,
      color: CATEGORY_COLORS[name as Category]
    }));
  }, [expenses]);

  // --- GENAI INSIGHT ---
  useEffect(() => {
    if (showChartModal) {
      const fetchInsight = async () => {
        setCatInsight("Thinking...");
        try {
          const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
          const prompt = `You are a ${mood} cat named ${CAT_PROFILES.find(c => c.id === catId)?.name || 'Kitty'}. 
          The user has a budget of $${budget} and has spent $${totalSpent.toFixed(2)}. 
          Mood: ${mood}.
          Expenses breakdown: ${chartData.map(c => `${c.name}: $${c.value}`).join(', ')}.
          Provide a short, witty, 1-2 sentence remark about their spending habits or financial health. Be in character (use meows/purrs if happy, hisses if angry).`;
          
          const response = await ai.models.generateContent({
            model: 'gemini-2.5-flash',
            contents: prompt,
          });
          if (response.text) {
            setCatInsight(response.text);
          }
        } catch (error) {
           console.error("GenAI Error:", error);
           // Fallback logic
           setCatInsight(spendingRatio > 1 
              ? "We've burned through the budget! The cat is stressed. Check the 'Other' category."
              : spendingRatio > 0.8 
              ? "Getting close to the limit. Maybe skip the extra treats?"
              : "Excellent financial health! The cat is thriving.");
        }
      };
      fetchInsight();
    }
  }, [showChartModal, budget, totalSpent, mood, spendingRatio, catId, chartData]);

  if (isLoading) {
    return (
      <div className="h-[100dvh] w-full flex items-center justify-center bg-[#FDFCF8]">
        <motion.div 
           animate={{ rotate: 360, scale: [1, 1.1, 1] }} 
           transition={{ duration: 1.5, repeat: Infinity }}
           className="w-16 h-16 border-4 border-[#8D6E63] border-t-transparent rounded-full" 
        />
      </div>
    );
  }

  return (
    <div className="h-[100dvh] w-full bg-[#FDFCF8] font-sans text-[#4E342E] flex flex-col relative overflow-hidden select-none">
      
      {/* Background Decor */}
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-[#EFEBE9]/40 rounded-full blur-[100px] pointer-events-none" />
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-[#D7CCC8]/30 rounded-full blur-[100px] pointer-events-none" />

      {/* Header */}
      <header className="flex-none px-6 pt-8 pb-4 flex justify-between items-center z-10">
        <div className="flex items-center space-x-3 bg-white/50 backdrop-blur-md p-2 pr-4 rounded-2xl shadow-sm border border-white/60">
           <div className="bg-[#EFEBE9] p-2 rounded-xl">
             <Heart className="w-5 h-5 text-[#8D6E63] fill-current" />
           </div>
           <div>
             <h1 className="text-lg font-bold text-[#4E342E] leading-none">PurrBudget</h1>
             <p className="text-[10px] text-[#A1887F] uppercase font-bold tracking-wider">3D Edition</p>
           </div>
        </div>

        <button 
          onClick={withSound(() => setShowBudgetModal(true))}
          className="bg-white/80 backdrop-blur-md pl-4 pr-2 py-2 rounded-full shadow-sm border border-white flex items-center space-x-3 hover:bg-white transition-all active:scale-95 group"
        >
          <div className="flex flex-col items-end leading-none">
            <span className={`text-sm font-extrabold ${spendingRatio > 1 ? 'text-red-500' : spendingRatio > 0.75 ? 'text-orange-500' : 'text-emerald-500'}`}>
              ${totalSpent.toFixed(0)}
            </span>
            <span className="text-[10px] text-[#A1887F] font-medium">of ${budget}</span>
          </div>
          <div className="bg-[#EFEBE9] p-1.5 rounded-full group-hover:bg-[#D7CCC8] transition-colors">
            <Edit2 className="w-3 h-3 text-[#5D4037]" />
          </div>
        </button>
      </header>

      {/* Main Content */}
      <main className="flex-1 flex flex-col items-center justify-center p-6 z-0 overflow-y-auto overflow-x-hidden no-scrollbar w-full">
        
        <div className="relative flex-none mb-8 w-full flex justify-center">
            {/* Wardrobe Button (Absolute positioned relative to cat area) */}
            <motion.button
                whileTap={{ scale: 0.9 }}
                onClick={withSound(() => setShowWardrobeModal(true))}
                className="absolute right-4 top-10 z-20 w-12 h-12 bg-white rounded-full shadow-md flex items-center justify-center border border-[#E7E5E4] text-[#A1887F]"
            >
                <Shirt className="w-6 h-6" />
            </motion.button>

            <AnimatePresence mode="wait">
                <motion.div 
                    key={mood}
                    initial={{ opacity: 0, y: 10, scale: 0.9 }}
                    animate={{ opacity: 1, y: 0, scale: 1 }}
                    exit={{ opacity: 0, scale: 0.9 }}
                    className="absolute -top-16 left-1/2 transform -translate-x-1/2 bg-white/90 backdrop-blur-sm px-4 py-2 rounded-2xl shadow-lg border border-white/50 whitespace-nowrap z-20"
                >
                    <span className={`text-sm font-bold ${
                        mood === 'happy' ? 'text-emerald-600' : 
                        mood === 'worried' ? 'text-orange-600' : 
                        'text-red-600'
                    }`}>
                        {isPurring ? "* Purrrrrr *" : (mood === 'happy' ? "Purrfectly balanced!" : 
                         mood === 'worried' ? "Meow? Spending a lot..." : 
                         "HISSS! Over budget!")}
                    </span>
                    <div className="absolute -bottom-1 left-1/2 transform -translate-x-1/2 w-3 h-3 bg-white rotate-45" />
                </motion.div>
            </AnimatePresence>
            
            <div className="animate-float">
                <ThreeDCat 
                    stage={stage} 
                    mood={mood} 
                    catId={catId} 
                    hatId={hatId} 
                    onClick={playPurrSound} 
                />
            </div>
        </div>

        {/* Growth Info */}
        <div className="flex-none w-full max-w-[280px] bg-white/50 backdrop-blur-md p-4 rounded-2xl border border-white/60 shadow-sm">
          <div className="flex justify-between items-center mb-2">
            <span className="text-xs font-bold text-[#A1887F] uppercase">Growth Stage</span>
            <span className="text-xs font-bold text-[#5D4037] bg-[#D7CCC8]/30 px-2 py-0.5 rounded-full uppercase">{stage}</span>
          </div>
          <div className="h-3 bg-[#EFEBE9] rounded-full overflow-hidden">
             <motion.div 
               className="h-full bg-gradient-to-r from-[#D7CCC8] to-[#8D6E63] rounded-full shadow-[0_0_10px_rgba(141,110,99,0.3)]"
               initial={{ width: 0 }}
               animate={{ width: `${growthProgress * 100}%` }}
               transition={{ type: 'spring', stiffness: 50 }}
             />
          </div>
        </div>

      </main>

      {/* Navigation */}
      <nav className="flex-none px-6 pb-8 pt-4 z-20 bg-gradient-to-t from-[#FDFCF8] via-[#FDFCF8]/90 to-transparent">
        <div className="flex justify-center items-end space-x-8">
          <NavButton 
            icon={<DollarSign className="w-6 h-6" />} 
            label="Analysis" 
            onClick={withSound(() => setShowChartModal(true))} 
          />

          <motion.button 
            whileHover={{ scale: 1.05 }}
            whileTap={{ scale: 0.95 }}
            onClick={withSound(() => setShowAddModal(true))}
            className="w-16 h-16 bg-gradient-to-tr from-[#8D6E63] to-[#6D4C41] text-white rounded-2xl shadow-xl shadow-[#8D6E63]/40 flex items-center justify-center border-[3px] border-white transform -translate-y-2"
          >
            <Plus className="w-8 h-8" strokeWidth={3} />
          </motion.button>

          <NavButton 
             icon={<TrendingUp className="w-6 h-6" />} 
             label="History" 
             onClick={withSound(() => {})} 
             active={false}
          />
        </div>
      </nav>

      {/* --- MODALS --- */}
      <AnimatePresence>
        {showAddModal && (
          <Modal onClose={withSound(() => setShowAddModal(false))}>
             <AddExpenseForm onAdd={handleAddExpense} />
          </Modal>
        )}
        {showBudgetModal && (
          <Modal onClose={withSound(() => setShowBudgetModal(false))} title="Monthly Budget">
             <SetBudgetForm currentBudget={budget} onSave={handleUpdateBudget} />
          </Modal>
        )}
        {showChartModal && (
          <Modal onClose={withSound(() => setShowChartModal(false))} title="Spending Breakdown">
             <ExpensePieChart data={chartData} />
             <div className="mt-6 p-4 bg-[#F5F5F4] rounded-xl border border-[#E7E5E4] flex items-start space-x-3">
               <AlertCircle className="w-5 h-5 text-[#8D6E63] flex-shrink-0 mt-0.5" />
               <div>
                 <span className="text-xs font-bold text-[#A1887F] uppercase block mb-1">Cat's Insight</span>
                 <p className="text-sm text-[#5D4037] leading-relaxed">
                   {catInsight || "Thinking..."}
                 </p>
               </div>
             </div>
          </Modal>
        )}
        {showWardrobeModal && (
            <Modal onClose={withSound(() => setShowWardrobeModal(false))} title="Cat Wardrobe">
                <div className="space-y-6">
                    <div>
                        <h3 className="text-xs font-bold text-[#A1887F] uppercase tracking-wider mb-3">Choose Cat</h3>
                        <div className="grid grid-cols-2 gap-3">
                            {CAT_PROFILES.map((cat) => (
                                <button
                                    key={cat.id}
                                    onClick={withSound(() => setCatId(cat.id))}
                                    className={`p-3 rounded-xl border flex flex-col items-center transition-all ${
                                        catId === cat.id 
                                        ? 'bg-[#EFEBE9] border-[#8D6E63] ring-1 ring-[#8D6E63]' 
                                        : 'bg-white border-[#E7E5E4]'
                                    }`}
                                >
                                    <span className="font-bold text-[#4E342E] text-sm">{cat.name}</span>
                                    <span className="text-[10px] text-[#A1887F]">{cat.description}</span>
                                </button>
                            ))}
                        </div>
                    </div>
                    <div>
                        <h3 className="text-xs font-bold text-[#A1887F] uppercase tracking-wider mb-3">Choose Hat</h3>
                        <div className="grid grid-cols-3 gap-3">
                            {HAT_PROFILES.map((hat) => (
                                <button
                                    key={hat.id}
                                    onClick={withSound(() => setHatId(hat.id))}
                                    className={`p-2 rounded-xl border flex flex-col items-center transition-all ${
                                        hatId === hat.id 
                                        ? 'bg-[#EFEBE9] border-[#8D6E63] ring-1 ring-[#8D6E63]' 
                                        : 'bg-white border-[#E7E5E4]'
                                    }`}
                                >
                                    <div className="w-6 h-6 rounded-full mb-1 border border-black/10 shadow-sm" style={{ backgroundColor: hat.color }} />
                                    <span className="text-[10px] font-bold text-[#4E342E]">{hat.name}</span>
                                </button>
                            ))}
                        </div>
                    </div>
                </div>
            </Modal>
        )}
      </AnimatePresence>
    </div>
  );
}

// --- SUB COMPONENTS ---

const NavButton = ({ icon, label, onClick, active }: any) => (
  <motion.button 
    whileHover={{ y: -2 }}
    whileTap={{ scale: 0.95 }}
    onClick={onClick}
    className={`flex flex-col items-center space-y-1 ${active === false ? 'opacity-50' : 'opacity-100'}`}
  >
    <div className="w-12 h-12 bg-white rounded-2xl shadow-lg border border-[#E7E5E4] flex items-center justify-center text-[#A1887F] hover:text-[#5D4037] hover:border-[#D7CCC8] transition-colors">
      {icon}
    </div>
    <span className="text-[10px] font-bold text-[#A1887F] uppercase tracking-wide">{label}</span>
  </motion.button>
);

const Modal = ({ children, onClose, title }: { children?: React.ReactNode, onClose: () => void, title?: string }) => (
  <motion.div 
    initial={{ opacity: 0 }}
    animate={{ opacity: 1 }}
    exit={{ opacity: 0 }}
    className="fixed inset-0 bg-[#4E342E]/30 backdrop-blur-[2px] z-50 flex items-end sm:items-center justify-center sm:p-4"
    onClick={onClose}
  >
    <motion.div 
      initial={{ y: "100%" }}
      animate={{ y: 0 }}
      exit={{ y: "100%" }}
      transition={{ type: "spring", damping: 25, stiffness: 300 }}
      className="bg-[#FDFCF8] w-full sm:max-w-sm rounded-t-[2rem] sm:rounded-3xl p-6 pb-10 sm:pb-6 shadow-[0_-10px_40px_rgba(0,0,0,0.1)] relative max-h-[80vh] overflow-y-auto"
      onClick={(e) => e.stopPropagation()}
    >
      <div className="w-12 h-1.5 bg-[#E7E5E4] rounded-full mx-auto mb-6 sm:hidden" />
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-xl font-bold text-[#4E342E]">{title || 'New Expense'}</h2>
        <button onClick={onClose} className="p-2 bg-[#F5F5F4] rounded-full hover:bg-[#E7E5E4] transition-colors">
          <X className="w-5 h-5 text-[#A1887F]" />
        </button>
      </div>
      {children}
    </motion.div>
  </motion.div>
);

const AddExpenseForm = ({ onAdd }: { onAdd: (amount: number, category: Category, note: string) => void }) => {
  const [amount, setAmount] = useState('');
  const [category, setCategory] = useState<Category>(Category.Food);
  const [note, setNote] = useState('');

  // Sounds are passed via props or global function in real app, but for this snippet we'll use inline standard
  // To keep it clean, assume parent handles sounds via wrapper or internal hook if needed, 
  // but here we just focus on logic.
  
  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!amount) return;
    onAdd(parseFloat(amount), category, note);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-5">
      <div>
        <label className="block text-[10px] font-bold text-[#A1887F] uppercase tracking-wider mb-2">Amount</label>
        <div className="relative">
          <span className="absolute left-4 top-3.5 text-[#A1887F] font-bold">$</span>
          <input 
            type="number" 
            autoFocus
            inputMode="decimal"
            value={amount}
            onChange={(e) => setAmount(e.target.value)}
            className="w-full bg-[#FAFAFA] border border-[#E7E5E4] rounded-2xl py-3 pl-8 pr-4 text-xl font-bold text-[#4E342E] focus:ring-2 focus:ring-[#8D6E63] focus:border-transparent outline-none transition-all"
            placeholder="0.00"
          />
        </div>
      </div>

      <div>
        <label className="block text-[10px] font-bold text-[#A1887F] uppercase tracking-wider mb-2">Category</label>
        <div className="grid grid-cols-3 gap-2">
          {Object.values(Category).map((cat) => (
            <button
              key={cat}
              type="button"
              onClick={() => setCategory(cat)}
              className={`p-3 rounded-xl text-xs font-bold transition-all border active:scale-95 ${
                category === cat 
                  ? 'bg-[#EFEBE9] border-[#8D6E63] text-[#5D4037] shadow-inner' 
                  : 'bg-white border-[#E7E5E4] text-[#A1887F] hover:bg-[#FAFAFA]'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>
      </div>

      <div>
        <label className="block text-[10px] font-bold text-[#A1887F] uppercase tracking-wider mb-2">Note</label>
        <input 
          type="text" 
          value={note}
          onChange={(e) => setNote(e.target.value)}
          className="w-full bg-[#FAFAFA] border border-[#E7E5E4] rounded-2xl py-3 px-4 text-sm text-[#4E342E] focus:ring-2 focus:ring-[#8D6E63] outline-none"
          placeholder="What did you buy?"
        />
      </div>

      <button 
        type="submit" 
        className="w-full bg-[#8D6E63] text-white font-bold py-4 rounded-2xl shadow-lg shadow-[#D7CCC8] hover:shadow-xl active:scale-98 transition-all mt-4"
      >
        Track Expense
      </button>
    </form>
  );
};

const SetBudgetForm = ({ currentBudget, onSave }: { currentBudget: number, onSave: (val: number) => void }) => {
  const [val, setVal] = useState(currentBudget.toString());

  return (
    <form onSubmit={(e) => { e.preventDefault(); onSave(parseFloat(val) || 0); }} className="space-y-4">
      <div className="bg-[#EFEBE9] p-4 rounded-2xl mb-4 border border-[#D7CCC8]">
        <p className="text-sm text-[#5D4037]">
          Setting a realistic budget helps keep your cat happy. If you spend more than this amount, the cat will get angry!
        </p>
      </div>
      <div>
        <label className="block text-[10px] font-bold text-[#A1887F] uppercase tracking-wider mb-2">Monthly Budget</label>
        <div className="relative">
          <span className="absolute left-4 top-3.5 text-[#A1887F] font-bold">$</span>
          <input 
            type="number" 
            autoFocus
            inputMode="decimal"
            value={val}
            onChange={(e) => setVal(e.target.value)}
            className="w-full bg-[#FAFAFA] border border-[#E7E5E4] rounded-2xl py-3 pl-8 pr-4 text-xl font-bold text-[#4E342E] focus:ring-2 focus:ring-[#8D6E63] focus:border-transparent outline-none transition-all"
          />
        </div>
      </div>
      <button 
        type="submit" 
        className="w-full bg-[#8D6E63] text-white font-bold py-4 rounded-2xl shadow-lg shadow-[#D7CCC8] hover:shadow-xl active:scale-98 transition-all mt-4"
      >
        Save Budget
      </button>
    </form>
  );
};